apiVersion: v1
kind: Service
metadata:
  name: voting-service-app
  labels:
    name: voting-service-app
    author: kireeti
spec:
  type: LoadBalacer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-pod
...